// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApiScrapingData.Infrastructure.Data;

#nullable disable

namespace WebApiScrapingData.Infrastructure.Migrations
{
    [DbContext(typeof(ScrapingContext))]
    [Migration("20251109003807_new_table_evolution")]
    partial class new_table_evolution
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("WebApiScrapingData.Domain.Class.Ability", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateModification")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description_CN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description_CO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description_DE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description_EN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description_ES")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description_FR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description_IT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description_JP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description_RU")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name_CN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name_CO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name_DE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name_EN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name_ES")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name_FR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name_IT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name_JP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name_RU")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserCreation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserModification")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("versionModification")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Abilities");
                });

            modelBuilder.Entity("WebApiScrapingData.Domain.Class.Attack", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateModification")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description_CN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description_CO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description_DE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description_EN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description_ES")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description_FR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description_IT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description_JP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description_RU")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name_CN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name_CO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name_DE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name_EN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name_ES")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name_FR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name_IT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name_JP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name_RU")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Power")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Precision")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("TypeAttackId")
                        .HasColumnType("bigint");

                    b.Property<long?>("TypePokId")
                        .HasColumnType("bigint");

                    b.Property<string>("UserCreation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserModification")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("versionModification")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TypeAttackId");

                    b.HasIndex("TypePokId");

                    b.ToTable("Attacks");
                });

            modelBuilder.Entity("WebApiScrapingData.Domain.Class.DataInfo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateModification")
                        .HasColumnType("datetime2");

                    b.Property<string>("DescriptionTalent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescriptionVx")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescriptionVy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Evolutions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NextUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Size")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Talent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Types")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserCreation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserModification")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Weakness")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Weight")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WhenEvolution")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("versionModification")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DataInfos");
                });

            modelBuilder.Entity("WebApiScrapingData.Domain.Class.EvolutionChain", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateModification")
                        .HasColumnType("datetime2");

                    b.Property<string>("Evolutions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserCreation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserModification")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("versionModification")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("EvolutionChain");
                });

            modelBuilder.Entity("WebApiScrapingData.Domain.Class.Game", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateModification")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name_CN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name_CO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name_DE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name_EN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name_ES")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name_FR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name_IT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name_JP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name_RU")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserCreation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserModification")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("versionModification")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("WebApiScrapingData.Domain.Class.Pokemon", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("BasicHappiness")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CaptureRate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateModification")
                        .HasColumnType("datetime2");

                    b.Property<string>("EggMoves")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("EvolutionChainId")
                        .HasColumnType("bigint");

                    b.Property<long?>("EvolvesFromId")
                        .HasColumnType("bigint");

                    b.Property<long?>("GameId")
                        .HasColumnType("bigint");

                    b.Property<int>("Generation")
                        .HasColumnType("int");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("Id_CN")
                        .HasColumnType("bigint");

                    b.Property<long>("Id_CO")
                        .HasColumnType("bigint");

                    b.Property<long>("Id_DE")
                        .HasColumnType("bigint");

                    b.Property<long>("Id_EN")
                        .HasColumnType("bigint");

                    b.Property<long>("Id_ES")
                        .HasColumnType("bigint");

                    b.Property<long>("Id_FR")
                        .HasColumnType("bigint");

                    b.Property<long>("Id_IT")
                        .HasColumnType("bigint");

                    b.Property<long>("Id_JP")
                        .HasColumnType("bigint");

                    b.Property<long>("Id_RU")
                        .HasColumnType("bigint");

                    b.Property<string>("Number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PathAnimatedImg")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PathAnimatedImgShiny")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PathImgLegacy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PathImgNormal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PathImgShiny")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PathSound")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PathSoundCurrent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PathSoundLegacy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PathSpriteLegacy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PathSpriteNormal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PathSpriteShiny")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StatAttack")
                        .HasColumnType("int");

                    b.Property<int>("StatAttackSpe")
                        .HasColumnType("int");

                    b.Property<int>("StatDefense")
                        .HasColumnType("int");

                    b.Property<int>("StatDefenseSpe")
                        .HasColumnType("int");

                    b.Property<int>("StatPv")
                        .HasColumnType("int");

                    b.Property<int>("StatSpeed")
                        .HasColumnType("int");

                    b.Property<int>("StatTotal")
                        .HasColumnType("int");

                    b.Property<string>("TypeEvolution")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UrlImg")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UrlSound")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UrlSprite")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserCreation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserModification")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("versionModification")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EvolutionChainId");

                    b.HasIndex("EvolvesFromId");

                    b.HasIndex("GameId");

                    b.HasIndex("Id_CN");

                    b.HasIndex("Id_CO");

                    b.HasIndex("Id_DE");

                    b.HasIndex("Id_EN");

                    b.HasIndex("Id_ES");

                    b.HasIndex("Id_FR");

                    b.HasIndex("Id_IT");

                    b.HasIndex("Id_JP");

                    b.HasIndex("Id_RU");

                    b.ToTable("Pokemons");
                });

            modelBuilder.Entity("WebApiScrapingData.Domain.Class.Pokemon_Ability", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("AbilityId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateModification")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("bit");

                    b.Property<long>("PokemonId")
                        .HasColumnType("bigint");

                    b.Property<string>("UserCreation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserModification")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("versionModification")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AbilityId");

                    b.HasIndex("PokemonId");

                    b.ToTable("Pokemon_Ability");
                });

            modelBuilder.Entity("WebApiScrapingData.Domain.Class.Pokemon_Attack", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("AttackId")
                        .HasColumnType("bigint");

                    b.Property<string>("CTCS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateModification")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Level")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("PokemonId")
                        .HasColumnType("bigint");

                    b.Property<string>("TypeLearn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserCreation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserModification")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("versionModification")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AttackId");

                    b.HasIndex("PokemonId");

                    b.ToTable("Pokemon_Attack");
                });

            modelBuilder.Entity("WebApiScrapingData.Domain.Class.Pokemon_EvolvesTo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateModification")
                        .HasColumnType("datetime2");

                    b.Property<long>("EvolveToId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("PokemonId")
                        .HasColumnType("bigint");

                    b.Property<string>("UserCreation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserModification")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WhenEvolutionCN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WhenEvolutionCO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WhenEvolutionDE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WhenEvolutionEN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WhenEvolutionES")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WhenEvolutionFR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WhenEvolutionIT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WhenEvolutionJP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WhenEvolutionRU")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("versionModification")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EvolveToId");

                    b.HasIndex("PokemonId");

                    b.ToTable("Pokemon_EvolveTo");
                });

            modelBuilder.Entity("WebApiScrapingData.Domain.Class.Pokemon_TypePok", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateModification")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("PokemonId")
                        .HasColumnType("bigint");

                    b.Property<long>("TypePokId")
                        .HasColumnType("bigint");

                    b.Property<string>("UserCreation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserModification")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("versionModification")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PokemonId");

                    b.HasIndex("TypePokId");

                    b.ToTable("Pokemon_TypePok");
                });

            modelBuilder.Entity("WebApiScrapingData.Domain.Class.Pokemon_Weakness", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateModification")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("PokemonId")
                        .HasColumnType("bigint");

                    b.Property<long>("TypePokId")
                        .HasColumnType("bigint");

                    b.Property<string>("UserCreation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserModification")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("versionModification")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PokemonId");

                    b.HasIndex("TypePokId");

                    b.ToTable("Pokemon_Weakness");
                });

            modelBuilder.Entity("WebApiScrapingData.Domain.Class.Quizz.Answer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateModification")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<long>("IsCorrectID")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsSelected")
                        .HasColumnType("bit");

                    b.Property<string>("Libelle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserCreation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserModification")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("versionModification")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Answers");
                });

            modelBuilder.Entity("WebApiScrapingData.Domain.Class.Quizz.Difficulty", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateModification")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Libelle_CN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Libelle_CO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Libelle_DE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Libelle_EN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Libelle_ES")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Libelle_FR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Libelle_IT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Libelle_JP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Libelle_RU")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserCreation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserModification")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("versionModification")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Difficulties");
                });

            modelBuilder.Entity("WebApiScrapingData.Domain.Class.Quizz.Question", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("DataObjectID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateModification")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Done")
                        .HasColumnType("bit");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<long?>("QuestionTypeId")
                        .HasColumnType("bigint");

                    b.Property<string>("UserCreation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserModification")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("versionModification")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QuestionTypeId");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("WebApiScrapingData.Domain.Class.Quizz.QuestionType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateModification")
                        .HasColumnType("datetime2");

                    b.Property<long?>("DifficultyId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsBlurred")
                        .HasColumnType("bit");

                    b.Property<bool>("IsGrayscale")
                        .HasColumnType("bit");

                    b.Property<bool>("IsHide")
                        .HasColumnType("bit");

                    b.Property<bool>("IsMultipleAnswers")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSameType")
                        .HasColumnType("bit");

                    b.Property<string>("Libelle_CN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Libelle_CO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Libelle_DE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Libelle_EN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Libelle_ES")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Libelle_FR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Libelle_IT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Libelle_JP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Libelle_RU")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NbAnswers")
                        .HasColumnType("int");

                    b.Property<int>("NbAnswersPossible")
                        .HasColumnType("int");

                    b.Property<string>("UserCreation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserModification")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("versionModification")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DifficultyId");

                    b.ToTable("QuestionTypes");
                });

            modelBuilder.Entity("WebApiScrapingData.Domain.Class.Quizz.Question_Answer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("AnswerId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateModification")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("QuestionId")
                        .HasColumnType("bigint");

                    b.Property<string>("UserCreation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserModification")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("versionModification")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AnswerId");

                    b.HasIndex("QuestionId");

                    b.ToTable("Question_Answer");
                });

            modelBuilder.Entity("WebApiScrapingData.Domain.Class.Quizz.Quizz", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateModification")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Done")
                        .HasColumnType("bit");

                    b.Property<bool>("Easy")
                        .HasColumnType("bit");

                    b.Property<bool>("Gen1")
                        .HasColumnType("bit");

                    b.Property<bool>("Gen2")
                        .HasColumnType("bit");

                    b.Property<bool>("Gen3")
                        .HasColumnType("bit");

                    b.Property<bool>("Gen4")
                        .HasColumnType("bit");

                    b.Property<bool>("Gen5")
                        .HasColumnType("bit");

                    b.Property<bool>("Gen6")
                        .HasColumnType("bit");

                    b.Property<bool>("Gen7")
                        .HasColumnType("bit");

                    b.Property<bool>("Gen8")
                        .HasColumnType("bit");

                    b.Property<bool>("Gen9")
                        .HasColumnType("bit");

                    b.Property<bool>("GenArceus")
                        .HasColumnType("bit");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Hard")
                        .HasColumnType("bit");

                    b.Property<string>("IdentityUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Normal")
                        .HasColumnType("bit");

                    b.Property<string>("UserCreation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserModification")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("versionModification")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdentityUserId");

                    b.ToTable("Quizzs");
                });

            modelBuilder.Entity("WebApiScrapingData.Domain.Class.Quizz.QuizzDifficulty", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateModification")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Easy")
                        .HasColumnType("bit");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Hard")
                        .HasColumnType("bit");

                    b.Property<bool>("Normal")
                        .HasColumnType("bit");

                    b.Property<long?>("QuizzId")
                        .HasColumnType("bigint");

                    b.Property<string>("ResumeQuestion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserCreation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserModification")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("versionModification")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QuizzId");

                    b.ToTable("QuizzDifficulties");
                });

            modelBuilder.Entity("WebApiScrapingData.Domain.Class.Quizz.Quizz_Question", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateModification")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("QuestionId")
                        .HasColumnType("bigint");

                    b.Property<long>("QuizzId")
                        .HasColumnType("bigint");

                    b.Property<string>("UserCreation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserModification")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("versionModification")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.HasIndex("QuizzId");

                    b.ToTable("Quizz_Question");
                });

            modelBuilder.Entity("WebApiScrapingData.Domain.Class.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("JwtId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Revoked")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Used")
                        .HasColumnType("bit");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("WebApiScrapingData.Domain.Class.TypeAttack", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateModification")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description_CN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description_CO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description_DE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description_EN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description_ES")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description_FR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description_IT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description_JP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description_RU")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name_CN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name_CO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name_DE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name_EN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name_ES")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name_FR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name_IT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name_JP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name_RU")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PathImg")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UrlImg")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserCreation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserModification")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("versionModification")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("TypeAttacks");
                });

            modelBuilder.Entity("WebApiScrapingData.Domain.Class.TypePok", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateModification")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImgColor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InfoColor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name_CN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name_CO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name_DE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name_EN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name_ES")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name_FR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name_IT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name_JP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name_RU")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PathAutoHome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PathFondGo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PathIconHome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PathMiniGo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PathMiniHome_CN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PathMiniHome_CO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PathMiniHome_DE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PathMiniHome_EN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PathMiniHome_ES")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PathMiniHome_FR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PathMiniHome_IT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PathMiniHome_JP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PathMiniHome_RU")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeColor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UrlAutoHome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UrlFondGo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UrlIconHome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UrlMiniGo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UrlMiniHome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserCreation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserModification")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("versionModification")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("TypesPok");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("WebApiScrapingData.Domain.Class.Attack", b =>
                {
                    b.HasOne("WebApiScrapingData.Domain.Class.TypeAttack", "TypeAttack")
                        .WithMany()
                        .HasForeignKey("TypeAttackId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("WebApiScrapingData.Domain.Class.TypePok", "TypePok")
                        .WithMany()
                        .HasForeignKey("TypePokId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("TypeAttack");

                    b.Navigation("TypePok");
                });

            modelBuilder.Entity("WebApiScrapingData.Domain.Class.Pokemon", b =>
                {
                    b.HasOne("WebApiScrapingData.Domain.Class.EvolutionChain", "EvolutionChain")
                        .WithMany("Pokemons")
                        .HasForeignKey("EvolutionChainId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("WebApiScrapingData.Domain.Class.Pokemon", "EvolvesFrom")
                        .WithMany()
                        .HasForeignKey("EvolvesFromId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("WebApiScrapingData.Domain.Class.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("WebApiScrapingData.Domain.Class.DataInfo", "CN")
                        .WithMany()
                        .HasForeignKey("Id_CN")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebApiScrapingData.Domain.Class.DataInfo", "CO")
                        .WithMany()
                        .HasForeignKey("Id_CO")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebApiScrapingData.Domain.Class.DataInfo", "DE")
                        .WithMany()
                        .HasForeignKey("Id_DE")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebApiScrapingData.Domain.Class.DataInfo", "EN")
                        .WithMany()
                        .HasForeignKey("Id_EN")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebApiScrapingData.Domain.Class.DataInfo", "ES")
                        .WithMany()
                        .HasForeignKey("Id_ES")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebApiScrapingData.Domain.Class.DataInfo", "FR")
                        .WithMany()
                        .HasForeignKey("Id_FR")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebApiScrapingData.Domain.Class.DataInfo", "IT")
                        .WithMany()
                        .HasForeignKey("Id_IT")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebApiScrapingData.Domain.Class.DataInfo", "JP")
                        .WithMany()
                        .HasForeignKey("Id_JP")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebApiScrapingData.Domain.Class.DataInfo", "RU")
                        .WithMany()
                        .HasForeignKey("Id_RU")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CN");

                    b.Navigation("CO");

                    b.Navigation("DE");

                    b.Navigation("EN");

                    b.Navigation("ES");

                    b.Navigation("EvolutionChain");

                    b.Navigation("EvolvesFrom");

                    b.Navigation("FR");

                    b.Navigation("Game");

                    b.Navigation("IT");

                    b.Navigation("JP");

                    b.Navigation("RU");
                });

            modelBuilder.Entity("WebApiScrapingData.Domain.Class.Pokemon_Ability", b =>
                {
                    b.HasOne("WebApiScrapingData.Domain.Class.Ability", "Ability")
                        .WithMany("Pokemon_Abilities")
                        .HasForeignKey("AbilityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebApiScrapingData.Domain.Class.Pokemon", "Pokemon")
                        .WithMany("Pokemon_Abilities")
                        .HasForeignKey("PokemonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ability");

                    b.Navigation("Pokemon");
                });

            modelBuilder.Entity("WebApiScrapingData.Domain.Class.Pokemon_Attack", b =>
                {
                    b.HasOne("WebApiScrapingData.Domain.Class.Attack", "Attack")
                        .WithMany("Pokemon_Attacks")
                        .HasForeignKey("AttackId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebApiScrapingData.Domain.Class.Pokemon", "Pokemon")
                        .WithMany("Pokemon_Attacks")
                        .HasForeignKey("PokemonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Attack");

                    b.Navigation("Pokemon");
                });

            modelBuilder.Entity("WebApiScrapingData.Domain.Class.Pokemon_EvolvesTo", b =>
                {
                    b.HasOne("WebApiScrapingData.Domain.Class.Pokemon", "EvolveTo")
                        .WithMany()
                        .HasForeignKey("EvolveToId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebApiScrapingData.Domain.Class.Pokemon", "Pokemon")
                        .WithMany()
                        .HasForeignKey("PokemonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EvolveTo");

                    b.Navigation("Pokemon");
                });

            modelBuilder.Entity("WebApiScrapingData.Domain.Class.Pokemon_TypePok", b =>
                {
                    b.HasOne("WebApiScrapingData.Domain.Class.Pokemon", "Pokemon")
                        .WithMany("Pokemon_TypePoks")
                        .HasForeignKey("PokemonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebApiScrapingData.Domain.Class.TypePok", "TypePok")
                        .WithMany("Pokemon_TypePoks")
                        .HasForeignKey("TypePokId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pokemon");

                    b.Navigation("TypePok");
                });

            modelBuilder.Entity("WebApiScrapingData.Domain.Class.Pokemon_Weakness", b =>
                {
                    b.HasOne("WebApiScrapingData.Domain.Class.Pokemon", "Pokemon")
                        .WithMany("Pokemon_Weaknesses")
                        .HasForeignKey("PokemonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebApiScrapingData.Domain.Class.TypePok", "TypePok")
                        .WithMany("Pokemon_Weaknesses")
                        .HasForeignKey("TypePokId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pokemon");

                    b.Navigation("TypePok");
                });

            modelBuilder.Entity("WebApiScrapingData.Domain.Class.Quizz.Question", b =>
                {
                    b.HasOne("WebApiScrapingData.Domain.Class.Quizz.QuestionType", "QuestionType")
                        .WithMany()
                        .HasForeignKey("QuestionTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("QuestionType");
                });

            modelBuilder.Entity("WebApiScrapingData.Domain.Class.Quizz.QuestionType", b =>
                {
                    b.HasOne("WebApiScrapingData.Domain.Class.Quizz.Difficulty", "Difficulty")
                        .WithMany()
                        .HasForeignKey("DifficultyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Difficulty");
                });

            modelBuilder.Entity("WebApiScrapingData.Domain.Class.Quizz.Question_Answer", b =>
                {
                    b.HasOne("WebApiScrapingData.Domain.Class.Quizz.Answer", "Answer")
                        .WithMany()
                        .HasForeignKey("AnswerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebApiScrapingData.Domain.Class.Quizz.Question", "Question")
                        .WithMany("Question_Answers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Answer");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("WebApiScrapingData.Domain.Class.Quizz.Quizz", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "IdentityUser")
                        .WithMany()
                        .HasForeignKey("IdentityUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("IdentityUser");
                });

            modelBuilder.Entity("WebApiScrapingData.Domain.Class.Quizz.QuizzDifficulty", b =>
                {
                    b.HasOne("WebApiScrapingData.Domain.Class.Quizz.Quizz", "Quizz")
                        .WithMany()
                        .HasForeignKey("QuizzId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Quizz");
                });

            modelBuilder.Entity("WebApiScrapingData.Domain.Class.Quizz.Quizz_Question", b =>
                {
                    b.HasOne("WebApiScrapingData.Domain.Class.Quizz.Question", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebApiScrapingData.Domain.Class.Quizz.Quizz", "Quizz")
                        .WithMany("Quizz_Questions")
                        .HasForeignKey("QuizzId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Question");

                    b.Navigation("Quizz");
                });

            modelBuilder.Entity("WebApiScrapingData.Domain.Class.RefreshToken", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebApiScrapingData.Domain.Class.Ability", b =>
                {
                    b.Navigation("Pokemon_Abilities");
                });

            modelBuilder.Entity("WebApiScrapingData.Domain.Class.Attack", b =>
                {
                    b.Navigation("Pokemon_Attacks");
                });

            modelBuilder.Entity("WebApiScrapingData.Domain.Class.EvolutionChain", b =>
                {
                    b.Navigation("Pokemons");
                });

            modelBuilder.Entity("WebApiScrapingData.Domain.Class.Pokemon", b =>
                {
                    b.Navigation("Pokemon_Abilities");

                    b.Navigation("Pokemon_Attacks");

                    b.Navigation("Pokemon_TypePoks");

                    b.Navigation("Pokemon_Weaknesses");
                });

            modelBuilder.Entity("WebApiScrapingData.Domain.Class.Quizz.Question", b =>
                {
                    b.Navigation("Question_Answers");
                });

            modelBuilder.Entity("WebApiScrapingData.Domain.Class.Quizz.Quizz", b =>
                {
                    b.Navigation("Quizz_Questions");
                });

            modelBuilder.Entity("WebApiScrapingData.Domain.Class.TypePok", b =>
                {
                    b.Navigation("Pokemon_TypePoks");

                    b.Navigation("Pokemon_Weaknesses");
                });
#pragma warning restore 612, 618
        }
    }
}
